[database]
host = "localhost"
port = 5432
username = "admin"
password = "secret"
max_connections = 20
enabled = true

[server]
address = "0.0.0.0"
port = 8080
timeout_seconds = 30

[features]
logging = true
caching = false
